-- Criando a tabela visitante
CREATE TABLE [VISITANTE]
(
    [COD_VISITANTE] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [RG] NVARCHAR(160)  NOT NULL,
    [EMAIL] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_VISITANTE] PRIMARY KEY ([COD_VISITANTE])
);

CREATE UNIQUE INDEX [IPK_VISITANTE] ON [VISITANTE]([COD_VISITANTE]);

-- Criando a tabela parque
CREATE TABLE [PARQUE]
(
    [COD_PARQUE] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_PARQUE] PRIMARY KEY ([COD_PARQUE])
);

CREATE UNIQUE INDEX [IPK_PARQUE] ON [PARQUE]([COD_PARQUE]);

-- Criando a tabela pontos turísticos
CREATE TABLE [PONTOS_TURISTICOS]
(
    [COD_PONTO_TURISTICO] INTEGER NOT NULL,
    [COD_PARQUE] INTEGER  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_PONTO_TURISTICO] PRIMARY KEY ([COD_PONTO_TURISTICO]),
    CONSTRAINT [FK_PARQUE] FOREIGN KEY ([COD_PARQUE]) REFERENCES PARQUE(COD_PARQUE)
);

CREATE UNIQUE INDEX [IPK_PONTOS_TURISTICOS] ON [PONTOS_TURISTICOS]([COD_PONTO_TURISTICO]);

-- Criando a tabela visita
CREATE TABLE [VISITA]
(
    [COD_VISITA] INTEGER NOT NULL,
    [COD_PARQUE] INTEGER NOT NULL,
    [COD_VISITANTE] INTEGER NOT NULL,
    CONSTRAINT [PK_VISITA] PRIMARY KEY ([COD_VISITA]),
  	CONSTRAINT [FK_PARQUE] FOREIGN KEY ([COD_PARQUE]) REFERENCES PARQUE(COD_PARQUE),
  	CONSTRAINT [FK_VISITANTE] FOREIGN KEY ([COD_VISITANTE]) REFERENCES VISITANTE(COD_VISITANTE)
);

CREATE UNIQUE INDEX [IPK_VISITA] ON [VISITA]([COD_VISITA]);

-- Criando a tabela visita pontos
CREATE TABLE [VISITA_PONTOS]
(
    [COD_VISITA_PONTOS] INTEGER NOT NULL,
    [COD_VISITA] INTEGER NOT NULL,
    [COD_PONTO_TURISTICO] INTEGER NOT NULL,
    CONSTRAINT [PK_VISITA_PONTOS] PRIMARY KEY ([COD_VISITA_PONTOS]),
 	CONSTRAINT [FK_VISITA] FOREIGN KEY ([COD_VISITA]) REFERENCES VISITA(COD_VISITA),
 	CONSTRAINT [FK_PONTO_TURISTICO] FOREIGN KEY ([COD_PONTO_TURISTICO]) REFERENCES PONTO_TURISTICO(COD_PONTO_TURISTICO)
);

CREATE UNIQUE INDEX [IPK_VISITA_PONTOS] ON [VISITA_PONTOS]([COD_VISITA_PONTOS]);

