-- Criando a tabela funcionário
CREATE TABLE [FUNCIONARIO]
(
    [COD_FUNCIONARIO] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [CPF] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [FUNCAO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_FUNCIONARIO] PRIMARY KEY ([COD_FUNCIONARIO])
);

CREATE UNIQUE INDEX [IPK_FUNCIONARIO] ON [FUNCIONARIO]([COD_FUNCIONARIO]);

-- Criando a tabela ônibus
CREATE TABLE [ONIBUS]
(
    [COD_ONIBUS] INTEGER NOT NULL,
    [MODELO] NVARCHAR(160)  NOT NULL,
    [TIPO] NVARCHAR(160)  NOT NULL,
    [PLACA] NVARCHAR(160)  NOT NULL,
    [COMBUSTIVEL] NVARCHAR(160)  NOT NULL,
    [AUTONOMIA] FLOAT(8,2)  NOT NULL,
    CONSTRAINT [PK_ONIBUS] PRIMARY KEY ([COD_ONIBUS])
);

CREATE UNIQUE INDEX [IPK_ONIBUS] ON [ONIBUS]([COD_ONIBUS]);

-- Criando a tabela relatório
CREATE TABLE [RELATORIO]
(
    [COD_RELATORIO] INTEGER NOT NULL,
    [DATA_INICIO] DATETIME  NOT NULL,
    [DATA_FIM] DATETIME  NOT NULL,
    [VLR_TOTAL] FLOAT(8,2)  NOT NULL,
    CONSTRAINT [PK_RELATORIO] PRIMARY KEY ([COD_RELATORIO])
);

CREATE UNIQUE INDEX [IPK_RELATORIO] ON [RELATORIO]([COD_RELATORIO]);

-- Criando a tabela assento
CREATE TABLE [ASSENTO]
(
    [COD_ASSENTO] INTEGER NOT NULL,
    [CATEGORIA] NVARCHAR(160) NOT NULL,
    [VALOR] FLOAT(8,2) NOT NULL,
    CONSTRAINT [PK_ASSENTO] PRIMARY KEY ([COD_ASSENTO])
);

CREATE UNIQUE INDEX [IPK_ASSENTO] ON [ASSENTO]([COD_ASSENTO]);

-- Criando a tabela passageiro
CREATE TABLE [PASSAGEIRO]
(
    [COD_PASSAGEIRO] INTEGER NOT NULL,
    [NOME] NVARCHAR(160) NOT NULL,
   	[CPF] NVARCHAR(160) NOT NULL,
   	[TELEFONE] NVARCHAR(160) NOT NULL,
    CONSTRAINT [PK_PASSAGEIRO] PRIMARY KEY ([COD_PASSAGEIRO])
);

CREATE UNIQUE INDEX [IPK_PASSAGEIRO] ON [PASSAGEIRO]([COD_PASSAGEIRO]);

-- Criando a tabela assentos passagem
CREATE TABLE [ASSENTOS_PASSAGEM]
(
    [COD_ASSENTOS_PASSAGEM] INTEGER NOT NULL,
    [COD_ASSENTO] INTEGER NOT NULL,
    [COD_PASSAGEM] INTEGER NOT NULL,
    CONSTRAINT [PK_ASSENTOS_PASSAGEM] PRIMARY KEY ([COD_ASSENTOS_PASSAGEM]),
    CONSTRAINT [FK_ASSENTO] FOREIGN KEY ([COD_ASSENTO]) REFERENCES ASSENTO(COD_ASSENTO),
 	CONSTRAINT [FK_PASSAGEM] FOREIGN KEY ([COD_PASSAGEM]) REFERENCES PASSAGEM(COD_PASSAGEM)   
);

CREATE UNIQUE INDEX [IPK_ASSENTOS_PASSAGEM] ON [ASSENTOS_PASSAGEM]([COD_ASSENTOS_PASSAGEM]);

-- Criando a tabela passagem
CREATE TABLE [PASSAGEM]
(
    [COD_PASSAGEM] INTEGER NOT NULL,
    [COD_PASSAGEIRO] INTEGER NOT NULL,
    CONSTRAINT [PK_PASSAGEM] PRIMARY KEY ([COD_PASSAGEM]),
    CONSTRAINT [FK_PASSAGEIRO] FOREIGN KEY ([COD_PASSAGEIRO]) REFERENCES PASSAGEIRO(COD_PASSAGEIRO)
);

CREATE UNIQUE INDEX [IPK_PASSAGEM] ON [PASSAGEM]([COD_PASSAGEM]);

-- Criando a tabela paradas passagem
CREATE TABLE [PARADAS_PASSAGEM]
(
    [COD_PARADAS_PASSAGEM] INTEGER NOT NULL,
    [COD_PASSAGEM] INTEGER NOT NULL,
    [LOCAL_PARADA] NVARCHAR(160) NOT NULL,
    [QTD] INTEGER NOT NULL,
    CONSTRAINT [PK_PARADAS_PASSAGEM] PRIMARY KEY ([COD_PARADAS_PASSAGEM]),
    CONSTRAINT [FK_PASSAGEM] FOREIGN KEY ([COD_PASSAGEM]) REFERENCES PASSAGEM(COD_PASSAGEM)
);

CREATE UNIQUE INDEX [IPK_PARADAS_PASSAGEM] ON [PARADAS_PASSAGEM]([COD_PARADAS_PASSAGEM]);

-- Criando a tabela tripulação
CREATE TABLE [TRIPULACAO]
(
    [COD_TRIPULACAO] INTEGER NOT NULL,
    [COD_PASSAGEIRO] INTEGER NOT NULL,
 	[COD_FUNCIONARIO] INTEGER NOT NULL,
    CONSTRAINT [PK_TRIPULACAO] PRIMARY KEY ([COD_TRIPULACAO]),
    CONSTRAINT [FK_PASSAGEIRO] FOREIGN KEY ([COD_PASSAGEIRO]) REFERENCES PASSAGEIRO(COD_PASSAGEIRO),
    CONSTRAINT [FK_FUNCIONARIO] FOREIGN KEY ([COD_FUNCIONARIO]) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
);

CREATE UNIQUE INDEX [IPK_TRIPULACAO] ON [TRIPULACAO]([COD_TRIPULACAO]);

-- Criando a tabela viagem
CREATE TABLE [VIAGEM]
(
    [COD_VIAGEM] INTEGER NOT NULL,
    [COD_ONIBUS] INTEGER NOT NULL,
 	[COD_PASSAGEM] INTEGER NOT NULL,
 	[ORIGEM] NVARCHAR(160) NOT NULL,
 	[DESTINO] NVARCHAR(160) NOT NULL,
 	[VALOR_TOTAL] FLOAT(8,2) NOT NULL,
 	[DATAHORA] DATETIME NOT NULL,
    CONSTRAINT [PK_VIAGEM] PRIMARY KEY ([COD_VIAGEM]),
    CONSTRAINT [FK_ONIBUS] FOREIGN KEY ([COD_ONIBUS]) REFERENCES ONIBUS(COD_ONIBUS),
    CONSTRAINT [FK_PASSAGEM] FOREIGN KEY ([COD_PASSAGEM]) REFERENCES PASSAGEM(COD_PASSAGEM)
);

CREATE UNIQUE INDEX [IPK_VIAGEM] ON [VIAGEM]([COD_VIAGEM]);
