-- Criando a tabela cliente
CREATE TABLE [CLIENTE]
(
    [COD_CLIENTE] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [EMAIL] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [CPF] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY ([COD_CLIENTE])
);

CREATE UNIQUE INDEX [IPK_CLIENTE] ON [CLIENTE]([COD_CLIENTE]);

-- Criando a tabela filme
CREATE TABLE [FILME]
(
    [COD_FILME] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [VLR_FILME] FLOAT(8,2)  NOT NULL,
    [QTD_ESTOQUE] INTEGER  NOT NULL,
    CONSTRAINT [PK_FILME] PRIMARY KEY ([COD_FILME])
);

CREATE UNIQUE INDEX [IPK_FILME] ON [FILME]([COD_FILME]);

-- Criando a tabela locação
CREATE TABLE [LOCACAO]
(
    [COD_LOCACAO] INTEGER NOT NULL,
    [COD_CLIENTE] INTEGER  NOT NULL,
    [VLR_LOCACAO] FLOAT(8,2)  NOT NULL,
    [VLR_MULTA] FLOAT(8,2)  NOT NULL,
    [DATA_LOCACAO] DATETIME  NOT NULL,
    [DATA_DEVOLUCAO] DATETIME  NOT NULL,
    CONSTRAINT [PK_LOCACAO] PRIMARY KEY ([COD_LOCACAO]),
    CONSTRAINT [FK_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE UNIQUE INDEX [IPK_LOCACAO] ON [LOCACAO]([COD_LOCACAO]);

-- Criando a tabela filmes locação
CREATE TABLE [FILMES_LOCACAO]
(
    [COD_FILMES_LOCACAO] INTEGER NOT NULL,
    [COD_LOCACAO] INTEGER NOT NULL,
    [COD_FILME] INTEGER NOT NULL,
    [QTD_FILME] INTEGER NOT NULL,
    CONSTRAINT [PK_FILMES_LOCACAO] PRIMARY KEY ([COD_FILMES_LOCACAO]),
  	CONSTRAINT [FK_LOCACAO] FOREIGN KEY ([COD_LOCACAO]) REFERENCES LOCACAO(COD_LOCACAO),
  	CONSTRAINT [FK_FILME] FOREIGN KEY ([COD_FILME]) REFERENCES FILME(COD_FILME)
);

CREATE UNIQUE INDEX [IPK_FILMES_LOCACAO] ON [FILMES_LOCACAO]([COD_FILMES_LOCACAO]);
