-- Criando a tabela cliente
CREATE TABLE [CLIENTE]
(
    [COD_CLIENTE] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY ([COD_CLIENTE])
);

-- Exemplo com AUTOINCREMENT
-- CREATE TABLE [CLIENTE]
-- (
-- [COD_CLIENTE] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
-- [NOME] NVARCHAR(160)  NOT NULL,
-- [TELEFONE] NVARCHAR(160)  NOT NULL,
-- [ENDERECO] NVARCHAR(160)  NOT NULL
-- );
-- INSERT INTO CLIENTE (NOME, TELEFONE, ENDERECO)
-- VALUES ('ARAMUNI', '98888-8888', 'Rua X');

CREATE UNIQUE INDEX [IPK_CLIENTE] ON [CLIENTE]([COD_CLIENTE]);

-- Criando a tabela forma pagamento
CREATE TABLE [FORMA_PAGAMENTO]
(
    [COD_FORMA_PAGAMENTO] INTEGER NOT NULL,
    [DES_FORMA_PAGAMENTO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_FORMA_PAGAMENTO] PRIMARY KEY ([COD_FORMA_PAGAMENTO])
);

CREATE UNIQUE INDEX [IPK_FORMA_PAGAMENTO] ON [FORMA_PAGAMENTO]([COD_FORMA_PAGAMENTO]);

-- Criando a tabela fornecedor
CREATE TABLE [FORNECEDOR]
(
    [COD_FORNECEDOR] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_FORNECEDOR] PRIMARY KEY ([COD_FORNECEDOR])
);

CREATE UNIQUE INDEX [IPK_FORNECEDOR] ON [FORNECEDOR]([COD_FORNECEDOR]);

-- Criando a tabela situacao_pedido
CREATE TABLE [SITUACAO_PEDIDO]
(
    [COD_SITUACAO_PEDIDO] INTEGER NOT NULL,
    [STATUS_PEDIDO] NVARCHAR(160)  NOT NULL,
    [STATUS_PAGAMENTO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_SITUACAO_PEDIDO] PRIMARY KEY ([COD_SITUACAO_PEDIDO])
);

CREATE UNIQUE INDEX [IPK_SITUACAO_PEDIDO] ON [SITUACAO_PEDIDO]([COD_SITUACAO_PEDIDO]);

-- Criando a tabela vendedor
CREATE TABLE [VENDEDOR]
(
    [COD_VENDEDOR] INTEGER NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [TELEFONE] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_VENDEDOR] PRIMARY KEY ([COD_VENDEDOR])
);

CREATE UNIQUE INDEX [IPK_VENDEDOR] ON [VENDEDOR]([COD_VENDEDOR]);

-- Criando a tabela tipo_produto
CREATE TABLE [TIPO_PRODUTO]
(
    [COD_TIPO_PRODUTO] INTEGER NOT NULL,
    [DES_TIPO_PRODUTO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_TIPO_PRODUTO] PRIMARY KEY ([COD_TIPO_PRODUTO])
);

CREATE UNIQUE INDEX [IPK_TIPO_PRODUTO] ON [TIPO_PRODUTO]([COD_TIPO_PRODUTO]);

-- Criando a tabela produto
CREATE TABLE [PRODUTO]
(
	[COD_PRODUTO] INTEGER NOT NULL,
	[COD_TIPO_PRODUTO] INTEGER NOT NULL,
	[NOME] NVARCHAR(160)  NOT NULL,
	[VLR_PRODUTO_COMPRA] FLOAT(8,2)  NOT NULL,
	[VLR_PRODUTO_VENDA] FLOAT(8,2)  NOT NULL,
	CONSTRAINT [PK_PRODUTO] PRIMARY KEY ([COD_PRODUTO]),
	CONSTRAINT [FK_TIPO_PRODUTO] FOREIGN KEY ([COD_TIPO_PRODUTO]) REFERENCES TIPO_PRODUTO(COD_TIPO_PRODUTO)
);

CREATE UNIQUE INDEX [IPK_PRODUTO] ON [PRODUTO]([COD_PRODUTO]);

-- Criando a tabela pedido_compra
CREATE TABLE [PEDIDO_COMPRA]
(
    [COD_PEDIDO_COMPRA] INTEGER NOT NULL,
    [COD_FORNECEDOR] INTEGER NOT NULL,
    [VLR_PEDIDO_COMPRA] FLOAT(8,2)  NOT NULL,
    CONSTRAINT [PK_PEDIDO_COMPRA] PRIMARY KEY ([COD_PEDIDO_COMPRA]),
    CONSTRAINT [FK_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE UNIQUE INDEX [IPK_PEDIDO_COMPRA] ON [PEDIDO_COMPRA]([COD_PEDIDO_COMPRA]);

-- Criando a tabela item_pedido_compra
CREATE TABLE [ITEM_PEDIDO_COMPRA]
(
    [COD_ITEM_PEDIDO_COMPRA] INTEGER NOT NULL,
    [COD_PEDIDO_COMPRA] INTEGER NOT NULL,
    [COD_PRODUTO] INTEGER NOT NULL,
    [QTD_ITEM_PEDIDO_COMPRA] INTEGER NOT NULL,
    CONSTRAINT [PK_ITEM_PEDIDO_COMPRA] PRIMARY KEY ([COD_ITEM_PEDIDO_COMPRA]),
    CONSTRAINT [FK_PEDIDO_COMPRA] FOREIGN KEY ([COD_PEDIDO_COMPRA]) REFERENCES PEDIDO_COMPRA(COD_PEDIDO_COMPRA),
	CONSTRAINT [FK_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE UNIQUE INDEX [IPK_ITEM_PEDIDO_COMPRA] ON [ITEM_PEDIDO_COMPRA]([COD_ITEM_PEDIDO_COMPRA]);

-- Criando a tabela pedido_venda
CREATE TABLE [PEDIDO_VENDA]
(
    [COD_PEDIDO_VENDA] INTEGER NOT NULL,
    [COD_CLIENTE] INTEGER NOT NULL,
    [COD_VENDEDOR] INTEGER NOT NULL,
    [COD_SITUACAO_PEDIDO] INTEGER NOT NULL,
    [COD_FORMA_PAGAMENTO] INTEGER NOT NULL,
    [DATA_PEDIDO] DATETIME NOT NULL,
    [VLR_PEDIDO_VENDA] FLOAT(8,2)  NOT NULL,
    CONSTRAINT [PK_PEDIDO_VENDA] PRIMARY KEY ([COD_PEDIDO_VENDA]),
    CONSTRAINT [FK_CLIENTE] FOREIGN KEY ([COD_CLIENTE]) REFERENCES CLIENTE(COD_CLIENTE),
	CONSTRAINT [FK_VENDEDOR] FOREIGN KEY ([COD_VENDEDOR]) REFERENCES VENDEDOR(COD_VENDEDOR),
	CONSTRAINT [FK_SITUACAO_PEDIDO] FOREIGN KEY ([COD_SITUACAO_PEDIDO]) REFERENCES SITUACAO_PEDIDO(COD_SITUACAO_PEDIDO),
    CONSTRAINT [FK_FORMA_PAGAMENTO] FOREIGN KEY ([COD_FORMA_PAGAMENTO]) REFERENCES FORMA_PAGAMENTO(COD_FORMA_PAGAMENTO)
);

CREATE UNIQUE INDEX [IPK_PEDIDO_VENDA] ON [PEDIDO_VENDA]([COD_PEDIDO_VENDA]);

-- Criando a tabela item_pedido_venda
CREATE TABLE [ITEM_PEDIDO_VENDA]
(
    [COD_ITEM_PEDIDO_VENDA] INTEGER NOT NULL,
    [COD_PEDIDO_VENDA] INTEGER NOT NULL,
    [COD_PRODUTO] INTEGER NOT NULL,
    [QTD_ITEM_PEDIDO_VENDA] INTEGER NOT NULL,
    CONSTRAINT [PK_ITEM_PEDIDO_VENDA] PRIMARY KEY ([COD_ITEM_PEDIDO_VENDA]),
    CONSTRAINT [FK_PEDIDO_VENDA] FOREIGN KEY ([COD_PEDIDO_VENDA]) REFERENCES PEDIDO_COMPRA(COD_PEDIDO_COMPRA),
	CONSTRAINT [FK_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO)
);

CREATE UNIQUE INDEX [IPK_ITEM_PEDIDO_VENDA] ON [ITEM_PEDIDO_VENDA]([COD_ITEM_PEDIDO_VENDA]);

-- Criando a tabela cotacao
CREATE TABLE [COTACAO]
(
    [COD_COTACAO] INTEGER NOT NULL,
    [COD_PRODUTO] INTEGER NOT NULL,
    [COD_FORNECEDOR] INTEGER NOT NULL,
    [VLR_COTACAO] FLOAT(8,2) NOT NULL,
    [UNIDADE_MEDIDA] NVARCHAR(160) NOT NULL,
    CONSTRAINT [PK_COTACAO] PRIMARY KEY ([COD_COTACAO]),
    CONSTRAINT [FK_PRODUTO] FOREIGN KEY ([COD_PRODUTO]) REFERENCES PRODUTO(COD_PRODUTO),
	CONSTRAINT [FK_FORNECEDOR] FOREIGN KEY ([COD_FORNECEDOR]) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE UNIQUE INDEX [IPK_COTACAO] ON [COTACAO]([COD_COTACAO]);

-- INSERT [Tabela CLIENTE]
INSERT INTO CLIENTE (COD_CLIENTE, NOME, TELEFONE, ENDERECO)
VALUES (1, 'Aramuni', '98888-8888', 'Rua X');

-- SELECT [Tabela CLIENTE]
SELECT * FROM CLIENTE;

-- UDATE [Tabela CLIENTE]
UPDATE CLIENTE SET NOME = 'Thiago' WHERE COD_CLIENTE = 1;

-- DELETE [Tabela CLIENTE]
DELETE FROM CLIENTE WHERE COD_CLIENTE  = 1;

-- INSERT [Tabela TIPO_PRODUTO]
INSERT INTO TIPO_PRODUTO (COD_TIPO_PRODUTO, DES_TIPO_PRODUTO)
VALUES (1, 'Bebida');

-- INSERT [Tabela PRODUTO]
INSERT INTO PRODUTO (COD_PRODUTO, COD_TIPO_PRODUTO, NOME, VLR_PRODUTO_COMPRA, VLR_PRODUTO_VENDA)
VALUES (1, 1, 'Skol', 8.00, 16.00);
