-- Criando a tabela tipo comunicado
CREATE TABLE [TIPO_COMUNICADO]
(
    [COD_TIPO_COMUNICADO] INTEGER NOT NULL,
    [TIPO_COMUNICADO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_TIPO_COMUNICADO] PRIMARY KEY ([COD_TIPO_COMUNICADO])
);

CREATE UNIQUE INDEX [IPK_TIPO_COMUNICADO] ON [TIPO_COMUNICADO]([COD_TIPO_COMUNICADO]);

-- Criando a tabela usuário
CREATE TABLE [USUARIO]
(
    [COD_USUARIO] INTEGER NOT NULL,
    [LOGIN] NVARCHAR(160)  NOT NULL,
    [SENHA] NVARCHAR(160)  NOT NULL,
    [EMAIL] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY ([COD_USUARIO])
);

CREATE UNIQUE INDEX [IPK_USUARIO] ON [USUARIO]([COD_USUARIO]);

-- Criando a tabela lotação
CREATE TABLE [LOTACAO]
(
    [COD_LOTACAO] INTEGER NOT NULL,
    [DESCRICAO] NVARCHAR(160)  NOT NULL,
    [ENDERECO] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_LOTACAO] PRIMARY KEY ([COD_LOTACAO])
 );

CREATE UNIQUE INDEX [IPK_LOTACAO] ON [LOTACAO]([COD_LOTACAO]);

-- Criando a tabela funcionário
CREATE TABLE [FUNCIONARIO]
(
    [COD_FUNCIONARIO] INTEGER NOT NULL,
    [COD_USUARIO] NVARCHAR(160)  NOT NULL,
    [COD_LOTACAO] NVARCHAR(160)  NOT NULL,
    [NOME] NVARCHAR(160)  NOT NULL,
    [MATRICULA] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_FUNCIONARIO] PRIMARY KEY ([COD_FUNCIONARIO]),
    CONSTRAINT [FK_USUARIO] FOREIGN KEY ([COD_USUARIO]) REFERENCES USUARIO(COD_USUARIO),
    CONSTRAINT [FK_LOTACAO] FOREIGN KEY ([COD_LOTACAO]) REFERENCES LOTACAO(COD_LOTACAO)
);

CREATE UNIQUE INDEX [IPK_FUNCIONARIO] ON [FUNCIONARIO]([COD_FUNCIONARIO]);

-- Criando a tabela comunicado
CREATE TABLE [COMUNICADO]
(
    [COD_COMUNICADO] INTEGER NOT NULL,
    [COD_FUNCIONARIO] INTEGER NOT NULL,
    [COD_TIPO_COMUNICADO] INTEGER NOT NULL,
    [MENSAGEM] NVARCHAR(160)  NOT NULL,
    [DATAHORA] DATETIME  NOT NULL,
    [STATUS] NVARCHAR(160)  NOT NULL,
    CONSTRAINT [PK_COMUNICADO] PRIMARY KEY ([COD_COMUNICADO]),
    CONSTRAINT [FK_FUNCIONARIO] FOREIGN KEY ([COD_FUNCIONARIO]) REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    CONSTRAINT [FK_TIPO_COMUNICADO] FOREIGN KEY ([COD_TIPO_COMUNICADO]) REFERENCES TIPO_COMUNICADO(COD_TIPO_COMUNICADO)
);

CREATE UNIQUE INDEX [IPK_COMUNICADO] ON [COMUNICADO]([COD_COMUNICADO]);
